# Generated by Django 5.1.4 on 2025-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_class', models.CharField(blank=True, max_length=255, null=True)),
                ('predicted_label', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True, verbose_name='Кластер')),
                ('probability', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
