# Generated by Django 5.1.4 on 2024-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_image_remove_uploadedimage_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
