# Generated by Django 5.1.4 on 2024-12-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0006_delete_imagefeed_image_predicted_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
