# Generated by Django 5.1.4 on 2024-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0008_alter_image_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
